apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirst-green-deployment
  labels:
    app: my-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
      - name: web-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
      imagePullPolicy: Always