apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirst-green-deployment
  labels:
    app: my-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
      - name: web-app
        image: europe-west4-docker.pkg.dev/notional-radio-450521-a4/my-artifact-repo/my-app:green
        ports:
        - containerPort: 80