name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - test

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: my-gke-cluster
  GKE_ZONE: europe-west4
  IMAGE: my-app
  GAR_ZONE: europe-west4
  GAR_REPO: my-artifact-repo

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # Configure Docker to use the gcloud credential helper
      - name: Docker configuration
        run: |
          gcloud auth configure-docker $GAR_ZONE-docker.pkg.dev

      # Build the Docker image with tag based on branch
      - name: Build Docker image
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            IMAGE_TAG=blue
            DEPLOYMENT_NAME=myfirst-blue-deployment
          else
            IMAGE_TAG=green
            DEPLOYMENT_NAME=myfirst-green-deployment
          fi
          docker build -t $GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG .

      # Push the Docker image to Artifact Registry
      - name: Push Docker image
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            IMAGE_TAG=blue
          else
            IMAGE_TAG=green
          fi
          docker push $GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG

      # Get credentials for GKE
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      # Deploy the Docker image to the respective Deployment
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME web-app=$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG
          kubectl rollout status deployment/$DEPLOYMENT_NAME